{
 "title": "Ephemeral Attack Lab",
 "tags": [ "cyberlab" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "*",
     "metrics": [
      { "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "event_type:authentication*",
     "metrics": [
      { "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Process Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "event_type:process_start",
     "metrics": [
      { "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Network / HTTP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "event_type:http_request",
     "metrics": [
      { "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "*",
     "metrics": [
      { "type": "logs" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}