services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: cyberlab-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "127.0.0.1:9201:9200"
    mem_limit: 1g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - cyberlab-platform
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    container_name: cyberlab-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=labgrafana
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - elasticsearch
    networks:
      - cyberlab-platform
    restart: unless-stopped

networks:
  cyberlab-platform:
    name: cyberlab-platform

volumes:
  elasticsearch-data:
